# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc ""
  homepage "https://katallaxie.github.io/run/"
  version "0.1.0-beta.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.2/run_0.1.0-beta.2_darwin_arm64.tar.gz"
      sha256 "4c7e0682a3529b2252b7aec62a5ff413fb38ee7ff6813483aa4ac7eeb378d30b"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.2/run_0.1.0-beta.2_darwin_amd64.tar.gz"
      sha256 "a04361e4ed85de896bf454ae4140695b7c0d922fa397260434dca1493566431f"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.2/run_0.1.0-beta.2_linux_amd64.tar.gz"
      sha256 "ca75de8e8860073497ca2662beed40501a7a7c67b5e689c52b6e81ccc55c6cd9"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.2/run_0.1.0-beta.2_linux_arm64.tar.gz"
      sha256 "dd1e0e8844bf64c16fc2d94646db16e63048a3ddb47467dfeab548c8a43b3e3b"

      def install
        bin.install "run"
      end
    end
  end

  depends_on "go" => :optional
end
