# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc ""
  homepage "https://andersnormal.github.io/run/"
  version "0.1.0-beta.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.1/run_0.1.0-beta.1_darwin_arm64.tar.gz"
      sha256 "0f0fd58874bd55a19fe4b20320613281ad8b80e8d731047e99758c8c028210bb"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.1/run_0.1.0-beta.1_darwin_amd64.tar.gz"
      sha256 "f8426ded34a6b30bfca10d66c0616ff84b518ad95dec079bd2bf7fd5c64f3f3b"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.1/run_0.1.0-beta.1_linux_arm64.tar.gz"
      sha256 "ceae90774d49949e52de162ff702d8e69bb237059e198299efd33a098e32601e"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.1/run_0.1.0-beta.1_linux_amd64.tar.gz"
      sha256 "99579c0b3cae24e7ab554812d938f319c96d5f1ef0a8f8b67a647b9ef401a8fa"

      def install
        bin.install "run"
      end
    end
  end

  depends_on "go" => :optional
end
