# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Run < Formula
  desc ""
  homepage "https://katallaxie.github.io/run/"
  version "0.1.0-beta.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.3/run_0.1.0-beta.3_darwin_arm64.tar.gz"
      sha256 "af2e5c07d698dda23ad8014af23128bf2c15059664fb8d2f52fab904a1abb8b8"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.3/run_0.1.0-beta.3_darwin_amd64.tar.gz"
      sha256 "04767a0f91aaffc7646747ddef383539f3467424ec510a8442e70125adeb252c"

      def install
        bin.install "run"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.3/run_0.1.0-beta.3_linux_arm64.tar.gz"
      sha256 "02bca3f27e964810394a130b45b3a95cde4798e81d6e716551e3b54c8ca39b2d"

      def install
        bin.install "run"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/katallaxie/run/releases/download/v0.1.0-beta.3/run_0.1.0-beta.3_linux_amd64.tar.gz"
      sha256 "ec85dab1ce569facf83b64961263f5d3b96866b33701fb4e71a601c569297492"

      def install
        bin.install "run"
      end
    end
  end

  depends_on "go" => :optional
end
